### ISSUE TITLE
Songs from "compilation" lists aren't omitted

### ISSUE THREAD

**Issue by stebo02** [P4lmeiras/allOfArtist#2]
When creating an All Of playlist for a popular artist, with both the "Only originals" and "With featured on" settings, the script adds tracks from compilation lists like "New Pop Hits" etc. These songs are just duplicates so having these added is undesirable. I don't think this was the case before but if it was, then this is a feature request to ignore compilation lists.

**Comment by P4lmeiras** [comment]
Originally the script didn't add songs from compilations, but I was unsatisfied with that as there are certain songs that are only present in said compilations (e.g., 'Diamonds Are Forever' by Arctic Monkeys). For this reason I modified the script to include compilations as long as there was no other song with the same name in the playlist, though it clearly is not being filtered as intended.
As soon as I can, I'll remove this from being a universal feature and add it as an extra option until I find a better solution.

**Comment by P4lmeiras** [comment]
Adding all songs including from compilations is now a separate option.
Let me know with a comment if the issue persists and I'll reopen it.
